#!/bin/bash

cd "$(dirname "$0")"
echo "PWD: `pwd`"
URL_PATH=$(dirname `pwd` | perl -p -e 's!^.*/public!!');
SCRIPT=sprite.sh
SCSS_SPRITE=../_sprite.scss
CSS_SPRITE=../sprite.css

FORCE=1 && [[ $1 == "--refresh" ]] && FORCE=0
TMP_FILES="../_*.scss ../_*.css ../*.png ../*.gif $SCSS_SPRITE $CSS_SPRITE";
if [[ $FORCE == 1 ]] || [[ $(find $TMP_FILES -not -newer $SCRIPT) ]]; then
    rm -v $TMP_FILES
fi;

DIRS=$(find ../ -type d -not -name '.' -not -name '..' -not -name 'scripts' -not -name 'tmp')
for DIR in $DIRS; do
    NAME=$(echo $DIR | perl -p -e 's!^\.*/*!!; s!/!-!');

    if [[ -f $DIR/.vertical ]]; then
        VERTICAL=1
        OFFSETX=0
        OFFSETY=10
        TILE=1x
    else
        VERTICAL=0
        OFFSETX=10
        OFFSETY=0
        TILE=x1
    fi

    GRAVITY=`cat $DIR/.gravity 2> /dev/null` && [[ GRAVITY ]] || GRAVITY="NorthWest"


    for EXT in png gif; do 
        #rm -vf ../${NAME}.$EXT
        SCSS="../__$NAME.$EXT.scss"
        CSS="../__$NAME.$EXT.css"
        SPRITE="../$NAME.$EXT"

        if [[ $FORCE == 1 ]] || [[ ! -f $SPRITE ]] || [[ ! -f $SCSS ]] || [[ $(find $DIR -name "*.$EXT" -depth 1 -newer $SPRITE -or -newer $SCSS ) ]]; then
            if [[ ! -f $DIR/.exclude ]] && [[ `ls $DIR/*.$EXT 2> /dev/null` ]]; then
                echo
                echo "SPRITE: $SPRITE | SCSS: $SCSS | CSS: $CSS | VERTICAL: $VERTICAL | GRAVITY: $GRAVITY"

                echo "\$sprite-$NAME-$EXT:  '$URL_PATH/$NAME.$EXT';" | tee -a $SCSS;

                POSX=$((-$OFFSETX));
                POSY=$((-$OFFSETY));
                for IMG in $DIR/*.$EXT; do
                    CSS_CLASS=$(basename $IMG .$EXT | perl -ne 'print lc')

                     WIDTH=$(identify $IMG | awk '// { print $3 }' | awk -F x '// { print $1 }')
                    HEIGHT=$(identify $IMG | awk '// { print $3 }' | awk -F x '// { print $2 }')

                    echo "\$sprite-$NAME-$CSS_CLASS-url:      '$URL_PATH/$NAME.$EXT';"  | tee -a $SCSS;
                    echo "\$sprite-$NAME-$CSS_CLASS-root-url: '$URL_PATH/${IMG/..\/\/}';" | tee -a $SCSS;
                    echo "\$sprite-$NAME-$CSS_CLASS-posx:     ${POSX}px;"               | tee -a $SCSS;
                    echo "\$sprite-$NAME-$CSS_CLASS-posy:     ${POSY}px;"               | tee -a $SCSS;
                    echo "\$sprite-$NAME-$CSS_CLASS-height:   ${HEIGHT}px;"             | tee -a $SCSS;
                    echo "\$sprite-$NAME-$CSS_CLASS-width:    ${WIDTH}px;"              | tee -a $SCSS;
                    echo "@mixin sprite-$NAME-$CSS_CLASS { background: transparent url($URL_PATH/$NAME.$EXT) no-repeat ${POSX}px ${POSY}px; height: ${HEIGHT}px; width: ${WIDTH}px; };" | tee -a $SCSS;
                    echo       ".sprite-$NAME-$CSS_CLASS { background: transparent url($URL_PATH/$NAME.$EXT) no-repeat ${POSX}px ${POSY}px; height: ${HEIGHT}px; width: ${WIDTH}px; }"  | tee -a $CSS;

                    if [[ $VERTICAL == 1 ]]; then
                        POSX=$((-$OFFSETX));
                        POSY=$(( POSY - HEIGHT - OFFSETY - OFFSETY ))
                    else
                        POSX=$(( POSX - WIDTH - OFFSETX - OFFSETX ))
                        POSY=$((-$OFFSETY));
                    fi
                done;
                montage -background none -gravity $GRAVITY -geometry +$OFFSETX+$OFFSETY -tile $TILE $DIR/*.$EXT $SPRITE;
            else
                rm -vf $SPRITE $SCSS $CSS;
		    fi
		fi
	done

    echo "//***** Autogenerated by scripts/sprite.sh *****//" > $SCSS_SPRITE;
    cat ../__*.scss >> $SCSS_SPRITE;

    echo "//***** Autogenerated by scripts/sprite.sh *****//" > $CSS_SPRITE;
    cat ../__*.css  >> $CSS_SPRITE;
done	
